---
title: "Strings and factors"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)

library(p8105.datasets)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Strings and regex (regular expressions)

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff")
str_detect(string_vec, "ff")
str_detect(string_vec, "e")

str_replace(string_vec, "jeff", "Jeff")
##replace "jeff" with Jeff"

str_replace(string_vec, "j", "Jeff")
str_replace(string_vec, "jeff", "")


```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")

## regular expressions

str_detect(string_vec, "^i think")
## ^ specifies begins with

str_detect(string_vec, "i think$")
## $ specifies ends with

## regular expressions and some combination of detect certain phrases, begins with, or ends with
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "bush")
str_detect(string_vec, "Bush")
str_detect(string_vec, "[Bb]ush")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

## how to detect a number first followed immediately by a letter?

str_detect(string_vec, "[0-9][a-zA-Z]")
str_detect(string_vec, "^[0-9][a-zA-Z]")
str_detect(string_vec, "[0-9][a-zA-Z]$")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

## want to detect 7 followed by any symbol

str_detect(string_vec, "7.11")
## the symbol . is a special character (like ^ or $) that specifically means any symbol afterwards

str_detect(string_vec, "7\\.11")
## the \\. specifies only . as the actual symbol
```


```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
## detect specifically the left bracket
```


## Factors

```{r}
factor_vec = factor(c("male", "male", "female", "female"))

factor_vec

as.numeric(factor_vec)
```

what happens if i relevel ...

```{r}
factor_vec = fct_relevel(factor_vec, "male")

factor_vec

as.numeric(factor_vec)
## behind the scenes coding of factors in R is one of the most confusing things.  in this case, R defaulted to alphabetical order for male and female 
```


## NSDUH -- strings

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

tabl_marj =
  read_html(url) %>% 
  html_nodes(css = "table") %>% 
  first() %>%
  html_table() %>%
  slice(-1) %>% 
  as_tibble()
```

```{r}
data_marj =
  tabl_marj %>% 
  select(-contains("P Value")) %>% 
  pivot_longer(
    -State, 
    names_to = "age_year",
    values_to = "percent"
  ) %>% 
  separate(age_year, into = c("age", "year"), sep = "\\(") %>% 
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    ##becareful here - as far as we know, only a-c and he is specifying this range only - if he is wrong, the code would break and that is desired
    percent = as.numeric(percent)
  ) %>% 
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```



## NSDUH -- factors
```{r}
data_marj %>% 
  filter(age == "12-17") %>% 
  mutate(
    State = fct_relevel(State, "Texas")
    ## Texas is made the default level and now a factor variable
  ) %>% 
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
  
data_marj %>% 
  filter(age == "12-17") %>% 
  mutate(
    State = fct_relevel(State, "Texas", "Oklahoma")
  ) %>% 
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

data_marj %>% 
  filter(age == "12-17") %>% 
  mutate(
    State = fct_reorder(State, percent)
    ##what this does is reorders your factor variable by some other variable that you are interested in, in this case this is percent
  ) %>% 
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

Another example in NYC dataset to work on factors - worth a look!

## Weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```

```{r}
weather_df %>% 
  mutate(
    name = fct_relevel(name, "Waikiki_HA")
    ##specifically makes Waikiki the first level
  ) %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()

weather_df %>% 
  mutate(
    name = fct_reorder(name, tmax)
    ## reorders by variable tmax
  ) %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()
```


```{r}
weather_df %>% 
  lm(tmax ~ name, data = .)
## R has defaulted reference group as Central Park - factor reorder is important in regression modeling

weather_df %>% 
  mutate(
  name = fct_reorder(name, tmax)
  ) %>% 
  lm(tmax ~ name, data = .)
```

some other examples